# Generated by Django 5.0.6 on 2024-05-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_id_alter_conversationmessage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
